### ISSUE TITLE
使用最新版fastjson， 还是报错

### ISSUE THREAD

**Issue by brucenan** [ipipdotnet/ipdb-java#10]
`com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0, fastjson-version 1.2.58
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:489)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1537)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_1_MetaData.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:689)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:378)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:282)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:555)
	at net.ipip.ipdb.Reader.init(Reader.java:53)
	at net.ipip.ipdb.Reader.<init>(Reader.java:25)
	at net.ipip.ipdb.Reader.<init>(Reader.java:21)
	at net.ipip.ipdb.City.<init>(City.java:17)`

**Comment by amazingWu** [comment]
也遇到这个问题，最后发现是文件的问题

**Comment by brucenan** [comment]
这边问题已定位，在maven配置中使用了properties和filter，在过滤替换的过程中，可能与ip库文件内部的${XXXX}内部冲突了，结果在打包过程中，把ip库文件给修改了。

解决办法：maven配置中，ip库文件跳过filter操作。

**Comment by boot-vue** [comment]
> 这边问题已定位，在maven配置中使用了properties和filter，在过滤替换的过程中，可能与ip库文件内部的${XXXX}内部冲突了，结果在打包过程中，把ip库文件给修改了。
> 
> 解决办法：maven配置中，ip库文件跳过filter操作。

对头
